// <auto-generated />
namespace FinalTest1.Contextos.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User3));
        
        string IMigrationMetadata.Id
        {
            get { return "201507281827112_User3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
